language: node_js
cache:
  directories:
    - node_modules

node_js:
  - 'stable'

install:
  - npm install

script:
  - npm run test

sudo: required

services:
  - docker


before_install:
# build latest image always
  - docker build -t amrutarajiv/node-docker-test .

after_success:
# IMPORTANT! Add the environment variables in Travis Build Environment (one time!)
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
# push image to docker hub
  - docker push amrutarajiv/node-docker-test;