sudo: required

language: node_js

services:
  - docker

before_script:
# build latest image always
  - docker build -t $DOCKER_USERNAME/node-docker-test .

script:
  - docker images $DOCKER_USERNAME/node-docker-test

after_success:
# IMPORTANT! Add the environment variables in Travis Build Environment (one time!)
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
# push image to docker hub
  - docker push $DOCKER_USERNAME/node-docker-test:latest;