language: node_js
cache:
  directories:
    - node_modules

node_js:
  - 'stable'

install:
  - npm install

services:
  - docker

env:
  # IMPORTANT! Add your docker slug here (commit once)
  - TRAVIS_REPO_SLUG=amrutarajiv/node-docker-test

script:
  - npm run test
  # build latest image always
  - docker build -t $TRAVIS_REPO_SLUG:$TRAVIS_BUILD_ID .

after_success:
  # IMPORTANT! Add the environment variables in Travis Build Environment (one time!)
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  # push image to docker hub
  - docker push $TRAVIS_REPO_SLUG:$TRAVIS_BUILD_ID