language: node_js
cache:
  directories:
    - node_modules

node_js:
  - 'stable'

install:
  - npm install

services:
  - docker

env:
  global:
    - DOCKER_USERNAME
    - DOCKER_PASSWORD

script:
  - npm run test
  # build latest image always
  - docker build -t amrutarajiv/node-docker-test:$TRAVIS_BUILD_ID .

after_success:
  # IMPORTANT! Add the environment variables in Travis Build Environment (one time!)
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  # push image to docker hub
  - docker push amrutarajiv/node-docker-test:$TRAVIS_BUILD_ID