sudo: required

language: node_js

services:
  - docker

before_script:
# build latest image always
  - docker build -t $DOCKER_USERNAME/node-docker-test .

script:
  - docker images $DOCKER_USERNAME/node-docker-test

deploy:
provider: heroku
api_key:
  secure: $HEROKU_API_KEY
app: heroku-ci-cd-app
